package com.team30.game.game_mechanics;


/**
 * A ID class used to uniquely identify every entity
 * Currently ID's are generated by adding one, off the previous ID
 */
// TODO Needs work
// TODO Needs a pretty print
public class ID {
    /**
     * Counter to assign new ID's
     */
    private static int idCount = 1;
    /**
     * The unique ID of the entity
     */
    public final int ID;
    /**
     * What "type" the entity has
     */
    public final EntityType type;

    public ID() {
        idCount += 1;
        this.ID = idCount;
        type = null;
    }

    public ID(EntityType type) {
        idCount += 1;
        this.ID = idCount;
        this.type = type;
    }
}